[fix] Downgrade okhttp 3.14.0 -> 3.13.1 to avoid UnrepeatableRequestBody NoSuchMethodErrors  (#1039)
## Before this PR

https://github.com/palantir/conjure-java-runtime/pull/1026 (which went into 4.20.1) inadvertently brought in a bump in okhttp to 3.14.0.
One of our internal libraries relied on `UnrepeatableRequestBody` which got removed in github.com/square/okhttp/pull/4676, and a solution using `RequestBody#isOneShot` couldn't be made that exhibits the previous behaviour.

## After this PR

Downgrading okhttp to 3.13.1, and adding a constraint to prevent accidental upgrades to 3.14.0 for the time being.