[fix] update message in uncaught exception handler
Turns out OOM and NoSuchMethodError will also trigger this. The assertion that this is a bug seems to cause people to short circuit any debugging they might otherwise have done.